<div id="guri_locator_block" style="clear:both;">
        <div id="guri_locator_filter">
        <div class="column_right">
                <div class="block-title">
                    <strong><span>Filter</span></strong>
                </div>
                <div class="block-content">
                     <form id="guri-store-locator-form" class="attributes" action="<?php echo $block->getFormAction(); ?>">
                               <div class="location-attribute">
                                <div class="attribute-label">Payment Methods</div>
                                <div class="input-box">
                                    <select name="payment_method[]" id="payment_method" multiple="multiple">
                                        <option value="">Please Select</option>
                                        <option value="6">Cash</option>
                                        <option value="7">Card</option>
                                        <option value="8">PayPal</option>
                                    </select>
                                </div>
                            </div>
                               <div class="location-attribute">
                                <div class="attribute-label">Parking Availability</div>
                                <div class="input-box">
                                    <select name="parking_availability" id="parking_availability">
                                        <option value="">Please Select</option>
                                        <option value="0">No</option>
                                        <option value="1">Yes</option>
                                    </select>
                                    <input type="hidden" name="ajax_filter"  value="storelocations"  />
                                </div>
                            </div>
                               <div class="location-attribute">
                                <div class="attribute-label">ATM</div>
                                <div class="input-box">
                                    <select name="atm" id="atm">
                                        <option value="">Please Select</option>
                                                <option value="0">No</option>
                                                <option value="1">Yes</option>
                                        </select>
                                </div>
                            </div>
                    </form>
                    <button class="button filter-attribute" title="Filter" id="guri-filter-attribute-id5c4af189372e2"><span><span>Filter</span></span></button>
                </div>
                    </div>
            </div>
    <div class="gurilocator_center">
        <div class="gurilocator_mapblock" style="width: ; height: ;">
            map will show here
        </div>
        <div class="gurilocator_store_list" style="width: ; height: ;">
        <div id="gurilocator_store_list">
            <?php if(count($block->listLocations()) > 0) {
                foreach ($block->listLocations() as $key => $value) {
                ?>
            <span name="leftLocation" data-mapid="gurilocator-map-canvas5c4af189374a6" data-amid="<?php echo $value['location_id']?>">
                    <div class="location_header"><?php echo $value['location_name']?></div> <br>
                        City: <?php echo $value['location_city']?> <br>
                        Zip: <?php echo $value['location_zip']?> <br>
                <div class="today_schedule">
                        Work Time Today:<span> 08:00 - 16:00<div class="locator_arrow"></div>
                    </span>
                </div>
                <div class="all_schedule" id="schedule3">
                        <div>Monday:<span>08:00 - 18:00</span></div>
                </div>
            </span>
            <?php } // for each ?>
            <?php } ?>
        </div>
        </div>
        </div>
</div>

<script>
    var AjaxUrl = "<?php echo $block->getBaseUrl().'storelocator/index' ?>"; 
</script>