<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Guri\StoreLocator\Model\Location\Source;

use Magento\Framework\Data\OptionSourceInterface;
use Magento\Framework\View\Model\PageLayout\Config\BuilderInterface;

/**
 * Class PageLayout
 */
class Countries implements OptionSourceInterface
{
    /**
     * @var \Magento\Framework\View\Model\PageLayout\Config\BuilderInterface
     */
    protected $pageLayoutBuilder;

    /**
     * @var array
     */
    protected $options;

    /**
     * Constructor
     *
     * @param BuilderInterface $pageLayoutBuilder
     */
    public function __construct(BuilderInterface $pageLayoutBuilder)
    {
        $this->pageLayoutBuilder = $pageLayoutBuilder;
    }

    /**
     * Get options
     *
     * @return array
     */
    public function toOptionArray()
    {
        if ($this->options !== null) {
            return $this->options;
        }

        $configOptions = array(
                        "AF" => "Afghanistan",  
                        "002" => "Africa",  
                        "AL" => "Albania",  
                        "DZ" => "Algeria",  
                        "AS" => "American Samoa",  
                        "019" => "Americas",  
                        "AD" => "Andorra",  
                        "AO" => "Angola",  
                        "AI" => "Anguilla",  
                        "AQ" => "Antarctica",  
                        "AG" => "Antigua &amp; Barbuda",  
                        "AR" => "Argentina",  
                        "AM" => "Armenia",  
                        "AW" => "Aruba",  
                        "AC" => "Ascension Island",  
                        "142" => "Asia",  
                        "053" => "Australasia",  
                        "AU" => "Australia",  
                        "AT" => "Austria",  
                        "AZ" => "Azerbaijan",  
                        "BS" => "Bahamas",  
                        "BH" => "Bahrain",  
                        "BD" => "Bangladesh",  
                        "BB" => "Barbados",  
                        "BY" => "Belarus",  
                        "BE" => "Belgium",  
                        "BZ" => "Belize",  
                        "BJ" => "Benin",  
                        "BM" => "Bermuda",  
                        "BT" => "Bhutan",  
                        "BO" => "Bolivia",  
                        "BA" => "Bosnia &amp; Herzegovina",  
                        "BW" => "Botswana",  
                        "BV" => "Bouvet Island",  
                        "BR" => "Brazil",  
                        "IO" => "British Indian Ocean Territory",  
                        "VG" => "British Virgin Islands",  
                        "BN" => "Brunei",  
                        "BG" => "Bulgaria",  
                        "BF" => "Burkina Faso",  
                        "BI" => "Burundi",  
                        "KH" => "Cambodia",  
                        "CM" => "Cameroon",  
                        "CA" => "Canada",  
                        "IC" => "Canary Islands",  
                        "CV" => "Cape Verde",  
                        "029" => "Caribbean",  
                        "BQ" => "Caribbean Netherlands",  
                        "KY" => "Cayman Islands",  
                        "CF" => "Central African Republic",  
                        "013" => "Central America",  
                        "143" => "Central Asia",  
                        "EA" => "Ceuta &amp; Melilla",  
                        "TD" => "Chad",  
                        "CL" => "Chile",  
                        "CN" => "China",  
                        "CX" => "Christmas Island",  
                        "CP" => "Clipperton Island",  
                        "CC" => "Cocos (Keeling) Islands",  
                        "CO" => "Colombia",  
                        "KM" => "Comoros",  
                        "CG" => "Congo - Brazzaville",  
                        "CD" => "Congo - Kinshasa",  
                        "CK" => "Cook Islands",  
                        "CR" => "Costa Rica",  
                        "HR" => "Croatia",  
                        "CU" => "Cuba",  
                        "CW" => "Curaçao",  
                        "CY" => "Cyprus",  
                        "CZ" => "Czech Republic",  
                        "CI" => "Côte d’Ivoire",  
                        "DK" => "Denmark",  
                        "DG" => "Diego Garcia",  
                        "DJ" => "Djibouti",  
                        "DM" => "Dominica",  
                        "DO" => "Dominican Republic",  
                        "014" => "Eastern Africa",  
                        "030" => "Eastern Asia",  
                        "151" => "Eastern Europe",  
                        "EC" => "Ecuador",  
                        "EG" => "Egypt",  
                        "SV" => "El Salvador",  
                        "GQ" => "Equatorial Guinea",  
                        "ER" => "Eritrea",  
                        "EE" => "Estonia",  
                        "ET" => "Ethiopia",  
                        "150" => "Europe",  
                        "EU" => "European Union",  
                        "FK" => "Falkland Islands",  
                        "FO" => "Faroe Islands",  
                        "FJ" => "Fiji",  
                        "FI" => "Finland",  
                        "FR" => "France",  
                        "GF" => "French Guiana",  
                        "PF" => "French Polynesia",  
                        "TF" => "French Southern Territories",  
                        "GA" => "Gabon",  
                        "GM" => "Gambia",  
                        "GE" => "Georgia",  
                        "DE" => "Germany",  
                        "GH" => "Ghana",  
                        "GI" => "Gibraltar",  
                        "GR" => "Greece",  
                        "GL" => "Greenland",  
                        "GD" => "Grenada",  
                        "GP" => "Guadeloupe",  
                        "GU" => "Guam",  
                        "GT" => "Guatemala",  
                        "GG" => "Guernsey",  
                        "GN" => "Guinea",  
                        "GW" => "Guinea-Bissau",  
                        "GY" => "Guyana",  
                        "HT" => "Haiti",  
                        "HM" => "Heard &amp; McDonald Islands",  
                        "HN" => "Honduras",  
                        "HK" => "Hong Kong SAR China",  
                        "HU" => "Hungary",  
                        "IS" => "Iceland",  
                        "IN" => "India",  
                        "ID" => "Indonesia",  
                        "IR" => "Iran",  
                        "IQ" => "Iraq",  
                        "IE" => "Ireland",  
                        "IM" => "Isle of Man",  
                        "IL" => "Israel",  
                        "IT" => "Italy",  
                        "JM" => "Jamaica",  
                        "JP" => "Japan",  
                        "JE" => "Jersey",  
                        "JO" => "Jordan",  
                        "KZ" => "Kazakhstan",  
                        "KE" => "Kenya",  
                        "KI" => "Kiribati",  
                        "XK" => "Kosovo",  
                        "KW" => "Kuwait",  
                        "KG" => "Kyrgyzstan",  
                        "LA" => "Laos",  
                        "419" => "Latin America",  
                        "LV" => "Latvia",  
                        "LB" => "Lebanon",  
                        "LS" => "Lesotho",  
                        "LR" => "Liberia",  
                        "LY" => "Libya",  
                        "LI" => "Liechtenstein",  
                        "LT" => "Lithuania",  
                        "LU" => "Luxembourg",  
                        "MO" => "Macau SAR China",  
                        "MK" => "Macedonia",  
                        "MG" => "Madagascar",  
                        "MW" => "Malawi",  
                        "MY" => "Malaysia",  
                        "MV" => "Maldives",  
                        "ML" => "Mali",  
                        "MT" => "Malta",  
                        "MH" => "Marshall Islands",  
                        "MQ" => "Martinique",  
                        "MR" => "Mauritania",  
                        "MU" => "Mauritius",  
                        "YT" => "Mayotte",  
                        "054" => "Melanesia",  
                        "MX" => "Mexico",  
                        "FM" => "Micronesia",  
                        "057" => "Micronesian Region",  
                        "017" => "Middle Africa",  
                        "MD" => "Moldova",  
                        "MC" => "Monaco",  
                        "MN" => "Mongolia",  
                        "ME" => "Montenegro",  
                        "MS" => "Montserrat",  
                        "MA" => "Morocco",  
                        "MZ" => "Mozambique",  
                        "MM" => "Myanmar (Burma)",  
                        "NA" => "Namibia",  
                        "NR" => "Nauru",  
                        "NP" => "Nepal",  
                        "NL" => "Netherlands",  
                        "AN" => "Netherlands Antilles",  
                        "NC" => "New Caledonia",  
                        "NZ" => "New Zealand",  
                        "NI" => "Nicaragua",  
                        "NE" => "Niger",  
                        "NG" => "Nigeria",  
                        "NU" => "Niue",  
                        "NF" => "Norfolk Island",  
                        "003" => "North America",  
                        "KP" => "North Korea",  
                        "015" => "Northern Africa",  
                        "021" => "Northern America",  
                        "154" => "Northern Europe",  
                        "MP" => "Northern Mariana Islands",  
                        "NO" => "Norway",  
                        "009" => "Oceania",  
                        "OM" => "Oman",  
                        "QO" => "Outlying Oceania",  
                        "PK" => "Pakistan",  
                        "PW" => "Palau",  
                        "PS" => "Palestinian Territories",  
                        "PA" => "Panama",  
                        "PG" => "Papua New Guinea",  
                        "PY" => "Paraguay",  
                        "PE" => "Peru",  
                        "PH" => "Philippines",  
                        "PN" => "Pitcairn Islands",  
                        "PL" => "Poland",  
                        "061" => "Polynesia",  
                        "PT" => "Portugal",  
                        "PR" => "Puerto Rico",  
                        "QA" => "Qatar",  
                        "RO" => "Romania",  
                        "RU" => "Russia",  
                        "RW" => "Rwanda",  
                        "RE" => "Réunion",  
                        "WS" => "Samoa",  
                        "SM" => "San Marino",  
                        "SA" => "Saudi Arabia",  
                        "SN" => "Senegal",  
                        "RS" => "Serbia",  
                        "SC" => "Seychelles",  
                        "SL" => "Sierra Leone",  
                        "SG" => "Singapore",  
                        "SX" => "Sint Maarten",  
                        "SK" => "Slovakia",  
                        "SI" => "Slovenia",  
                        "SB" => "Solomon Islands",  
                        "SO" => "Somalia",  
                        "ZA" => "South Africa",  
                        "005" => "South America",  
                        "GS" => "South Georgia &amp; South Sandwich Islands",  
                        "KR" => "South Korea",  
                        "SS" => "South Sudan",  
                        "035" => "Southeast Asia",  
                        "018" => "Southern Africa",  
                        "034" => "Southern Asia",  
                        "039" => "Southern Europe",  
                        "ES" => "Spain",  
                        "LK" => "Sri Lanka",  
                        "BL" => "St. Barthélemy",  
                        "SH" => "St. Helena",  
                        "KN" => "St. Kitts &amp; Nevis",  
                        "LC" => "St. Lucia",  
                        "MF" => "St. Martin",  
                        "PM" => "St. Pierre &amp; Miquelon",  
                        "VC" => "St. Vincent &amp; Grenadines",  
                        "SD" => "Sudan",  
                        "SR" => "Suriname",  
                        "SJ" => "Svalbard &amp; Jan Mayen",  
                        "SZ" => "Swaziland",  
                        "SE" => "Sweden",  
                        "CH" => "Switzerland",  
                        "SY" => "Syria",  
                        "ST" => "São Tomé &amp; Príncipe",  
                        "TW" => "Taiwan",  
                        "TJ" => "Tajikistan",  
                        "TZ" => "Tanzania",  
                        "TH" => "Thailand",  
                        "TL" => "Timor-Leste",  
                        "TG" => "Togo",  
                        "TK" => "Tokelau",  
                        "TO" => "Tonga",  
                        "TT" => "Trinidad &amp; Tobago",  
                        "TA" => "Tristan da Cunha",  
                        "TN" => "Tunisia",  
                        "TR" => "Turkey",  
                        "TM" => "Turkmenistan",  
                        "TC" => "Turks &amp; Caicos Islands",  
                        "TV" => "Tuvalu",  
                        "UM" => "U.S. Outlying Islands",  
                        "VI" => "U.S. Virgin Islands",  
                        "UG" => "Uganda",  
                        "UA" => "Ukraine",  
                        "AE" => "United Arab Emirates",  
                        "GB" => "United Kingdom",  
                        "US" => "United States",  
                        "ZZ" => "Unknown Region",  
                        "UY" => "Uruguay",  
                        "UZ" => "Uzbekistan",  
                        "VU" => "Vanuatu",  
                        "VA" => "Vatican City",  
                        "VE" => "Venezuela",  
                        "VN" => "Vietnam",  
                        "WF" => "Wallis &amp; Futuna",  
                        "011" => "Western Africa",  
                        "145" => "Western Asia",  
                        "155" => "Western Europe",  
                        "EH" => "Western Sahara",  
                        "001" => "World",  
                        "YE" => "Yemen",  
                        "ZM" => "Zambia",  
                        "ZW" => "Zimbabwe",  
                        "AX" => "Åland Islands"
                        );
        $options = [];
        foreach ($configOptions as $key => $value) {
            $options[] = [
                'label' => $value,
                'value' => $key,
            ];
        }
        $this->options = $options;

        return $this->options;
    }
}
